### ISSUE TITLE
‘EOF while reading’ when passing no arguments to jmh task

### ISSUE THREAD

**Issue by glts** [jgpc42/lein-jmh#1]
All invocations of this task using just `lein jmh` are currently broken,
because of the default argument `""` that is passed to
`leiningen.jmh/jmh`. `""` cannot be read with `read-string`.

Try `lein jmh` in lein-jmh’s own sample project for repro.

**Comment by jgpc42** [comment]
Thank you very much @glts  for the bug report. I didn't realize that `read-string` does not return `nil` if passed the empty string like `clojure.edn/read-string` does, which I used previously.

Fixed [here](https://github.com/jgpc42/lein-jmh/commit/c7ea0376ae1e1975f990cf00c809138d07759ce9). Released patch version 0.1.1.

**Comment by glts** [comment]
This is working for me now, thank you @jgpc42
