### ISSUE TITLE
Option for printing results in an easy to read, tabular format

### ISSUE THREAD

**Issue by glts** [jgpc42/lein-jmh#2]
This is a feature request for your consideration.

lein-jmh does a very fine job as a thin wrapper around jmh-clojure, but
I believe the default data-oriented presentation of the benchmark
results is not easy to use for a human reader.

JMH itself presents benchmark results in a table-like format, where
differences between benchmarks really can be seen at a glance.

Please consider providing an option for outputting results in a similar
human-readable at-a-glance format. Thank you!

**Comment by jgpc42** [comment]
I agree. Would something like the output of `lein jmh :profilers` be suitable? Something like:

```
:fn         :name  :params       :score
----------  -----  ------------  -------
my.ns/foo   :bar   {:x 2, :y 3}  42.0
my.ns/quux                       10000.0
```

Maybe by running `lein jmh '{:format :table, :only [:fn :name :params :score]}'`

**Comment by jgpc42** [comment]
I have implemented the above. I'd appreciate your feedback.

Here is the output from running `lein jmh '{:format :table}'` in the sample project (I added an additional benchmark with a parameter):

```
:fn/method                 :name  :mode         :samples  :score         :threads  :params
-------------------------  -----  ------------  --------  -------------  --------  -----------
(fn* [] (Thread/sleep 1))  expr   :single-shot  1         0.001634 s/op  1
clojure.core/rand                 :single-shot  1         1.01E-4 s/op   1         {:limit 42}
```

I need to account for whether a `:fn` or external class `:method` was benchmarked so I'm using a combined column: `:fn/method`. 

I also need to expand any nested `:profilers` and `:percentiles` maps. This is the output of running `lein jmh '{:exclude [:mode :name :threads], :format :table, :mode :sample, :profilers "gc"}'`:

```
:fn/method                         :samples  :score             :score-error  :params
---------------------------------  --------  -----------------  ------------  -----------
(fn* [] (Thread/sleep 1))          778       0.001284 s/op      4.2E-5
  0.0%                             1         0.001007 s/op
  0.5%                             1         0.001463 s/op
  0.9%                             1         0.001497 s/op
  0.95%                            1         0.001503 s/op
  0.99%                            1         0.001998 s/op
  0.999%                           1         0.008282 s/op
  0.9999%                          1         0.008282 s/op
  1.0%                             1         0.008282 s/op
  gc.alloc.rate                    1         0.075529 MB/sec
  gc.alloc.rate.norm               1         152.822622 B/op
  gc.count                         1         0.0 counts
clojure.core/rand                  36151     0.0 s/op                         {:limit 42}
  0.0%                             1         0.0 s/op
  0.5%                             1         0.0 s/op
  0.9%                             1         0.0 s/op
  0.95%                            1         0.0 s/op
  0.99%                            1         0.0 s/op
  0.999%                           1         0.0 s/op
  0.9999%                          1         2.1E-5 s/op
  1.0%                             1         4.0E-5 s/op
  gc.alloc.rate                    1         564.047087 MB/sec
  gc.alloc.rate.norm               1         24.004829 B/op
  gc.churn.PS_Eden_Space           1         579.526641 MB/sec
  gc.churn.PS_Eden_Space.norm      1         24.663611 B/op
  gc.churn.PS_Survivor_Space       1         0.020816 MB/sec
  gc.churn.PS_Survivor_Space.norm  1         8.86E-4 B/op
  gc.count                         1         17.0 counts
  gc.time                          1         10.0 ms
``` 

I added an `:exclude` option, demonstrated above. I wasn't exactly sure how to display the data from the profiler and `:sample` mode. I'm currently just  indenting by two spaces.

**Comment by glts** [comment]
Unfortunately I don’t think I have any deep insights that I could share.
And the exact format is probably a matter of personal preference.

What I can share is an experience report on my recent use of criterium
for benchmarking. Criterium produces somewhat verbose output, so I wrote
[a bit of
code](https://github.com/glts/couplet/blob/v0.0.5/benchmark/couplet/core_benchmark.clj#L39-L69)
around criterium’s `benchmark` to adapt it for purposes of quick visual
inspection and quick iteration. Here’s the format I settled on:

```
Reduce/iterate ASCII
  8460× couplet-codepoints-count                   7.155ms±0.04 (outliers 1/60)
  3360× couplet-transducing-codepoints-count      18.109ms±0.07 (outliers 1/60)
  1740× couplet-lazy-codepoints-count             34.944ms±0.12 (outliers 1/60)
   420× couplet-naive-lazy-codepoints-count      160.323ms±0.73
  1680× couplet-chunked-lazy-codepoints-count     36.960ms±0.14 (outliers 1/60)
  6840× clojure-char-count                         8.888ms±0.06 (outliers 2/60)
   480× clojure-lazy-char-count                  128.154ms±0.38 (outliers 1/60)
759960× jdk-char-sequence-chars-count             79.119µs±0.22
 19560× jdk-char-sequence-code-points-count        3.085ms±0.01

Fold
 17880× couplet-folding-codepoints-count           3.365ms±0.02
   960× couplet-fold-frequencies                  67.001ms±0.52
   300× couplet-reduce-frequencies               246.952ms±1.15 (outliers 4/60)

...
```

I am now in the process of porting these benchmarks to
jmh-clojure/lein-jmh – hence this feature request.

For me, the crucial feature of any such format is that the results can
be taken it at a glance. No scanning around for the interesting bits. I
think the JMH format is fine, as is the one your proposed. That is all I
have for now, will try it later. Thanks again.

**Comment by jgpc42** [comment]
I've deployed 0.2.0-SNAPSHOT. See `lein help jmh` for the new option documentation.

I'm still not exactly sure on how to uniformly format the `:score` values. JMH uses many different measurement units depending on the selected profilers, modes, etc. For now I'm just aligning them to the right:

```
:fn/method                         :mode    :samples  :score               :score-error  
---------------------------------  -------  --------  -------------------  ------------  
(fn* [] (Thread/sleep 1))          :sample  94        10.779495    ms/op   4.336668 
  0.0%                                      1         1.01888      ms/op
  ...     
  gc.alloc.rate                             1         0.128395     MB/sec
  gc.alloc.rate.norm                        1         2176.680851  B/op
  gc.count                                  1         0.0          counts
```

As an aside, your `couplet` library looks very cool! I've done my fair share of Unicode-related work. I'll be giving the `walkthrough.clj` a try when I get the time.

**Comment by glts** [comment]
Have tried the new format and it works very well for me. Thank you very
much!

**Comment by jgpc42** [comment]
Deployed 0.2.0 proper. Thanks again for this feature request. I'm using `:table` format now almost exclusively!
